preprocessing:
  classes:
    - 'toxic'
    - 'severe_toxic'
    - 'obscene'
    - 'threat'
    - 'insult'
    - 'identity_hate'
  input_trainset: '/Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/mini_train.csv'
  input_testset: '/Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/mini_test.csv'
  input_id_column: 'id'
  input_text_column: 'comment_text'
  split_ratio: 0.3
  random_seed: 0
training:
  learning_rate: 1.0
  dropout_rate: 0.5
  batch_size: 32
  batch_normalization: True
  optimizer: 'sgd'
  epochs: 2
  gradient_cliping: True
predict:
  output_path: '/Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/mini_submission.csv'

