preprocessing:
  split_ratio: 0.3
  input_trainset: './data/train.csv'
  input_testset: './data/test.csv'
  random_seed: 0
  classes:
    - 'toxic'
    - 'severe_toxic'
    - 'obscene'
    - 'threat'
    - 'insult'
    - 'identity_hate'
  input_text_column: 'comment_text'
  input_id_column: 'id'
training:
  learning_rate: 1.0
  dropout_rate: 0.5
  batch_normalization: True
  optimizer: 'sgd'
  epochs: 10
  gradient_cliping: True
predict:
  output_path: './data/submission.csv'