preprocessing:
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  embedding_dim: 200
  input_convertor: nn_vectorization
  input_id_column: id
  input_testset: /Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/mini_test.csv
  input_text_column: comment_text
  input_trainset: /Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/mini_train.csv
  maxlen: 128
  pretrained_embedding_file: /Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/glove/glove.twitter.27B.200d.txt
  random_seed: 0
  split_ratio: 0.3
training:
  batch_normalization: true
  batch_size: 32
  dropout_rate: 0.5
  embedding_dim: 200
  epochs: 1
  gradient_cliping: true
  learning_rate: 0.8
  maxlen: 128
  model_name: cnnglove
  optimizer: sgd
predict:
  output_path: /Users/songyihe/Documents/Study/AI Projects/large-datasets/toxic-comments/mini_submission.csv
